version: '3'
services:
  web:
    # this will build the current docker file
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure:2
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: flyway_r2dbc_sample_db
    volumes:
      - /Users/chrisjones/DockerCompose/db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5430:5430"